# Food Delivery Data Analysis

 

### Context

The growth of online food delivery platforms has transformed how people access restaurant services in large metropolitan cities. Busy professionals, students, and families increasingly depend on these platforms to order meals conveniently through mobile applications.

FoodHub is an online food aggregation platform that connects customers with multiple restaurants through a single mobile application. Customers can browse restaurant menus, place orders, and receive their meals through delivery personnel assigned by the platform.

Understanding customer ordering behavior, restaurant performance, and delivery efficiency is essential for improving service quality. By analyzing order data collected through the platform, valuable insights can be generated to support operational decisions and improve the overall customer experience.

### Objective
**The company wants to analyze this data to better understand:**
**As a Data Scientist working with this food delivery company, my task is to analyze the order data and generate insights that will help the company:**

* Customer ordering behavior
* Demand patterns for different restaurants
* Popular cuisines among customers
* Delivery performance and service efficiency
* Improve delivery efficiency
* Identify high-demand restaurants and cuisines
* Enhance customer satisfaction
* Support business growth and decision making

### Project Goal
By analyzing this dataset, the goal is to generate actionable insights that will help the food delivery platform to:
Identify the most popular restaurants and cuisines
Understand customer ordering patterns
Evaluate restaurant preparation performance
Measure delivery efficiency
Improve overall customer experience



### Data Description
The data contains the different data related to a food order. The detailed data dictionary is given below.

### Data Dictionary
* order_id: Unique ID of the order
* customer_id: ID of the customer who ordered the food
* taurant_name: Name of the restaurant
* cuisine_type: Cuisine ordered by the customer
* cost: Cost of the order
* day_of_the_week: Indicates whether the order is placed on a weekday or weekend (The weekday is from Monday to Friday and the weekend is Saturday and Sunday)
* rating: Rating given by the customer out of 5
* food_preparation_time: Time (in minutes) taken by the restaurant to prepare the food. This is calculated by taking the difference between the * * * timestamps of the restaurant's order confirmation and the delivery person's pick-up confirmation.
* delivery_time: Time (in minutes) taken by the delivery person to deliver the food package. This is calculated by taking the difference between the timestamps of the delivery person's pick-up confirmation and drop-off information

### Importing the necessary Libraries for the project

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.style as style
%matplotlib inline

### Loading or importing  the necessary dataset for the project

In [4]:
df = pd.read_csv("foodhub_order.csv")

### Doing the sanity check of the Dataset

In [5]:
#THIS IS TO CHECK FOR THE FIRST FIVE ROWS AND THE COLUMNS IN OUR DATASET
df.head()

,order_id,customer_id,restaurant_name,cuisine_type,cost_of_the_order,day_of_the_week,rating,food_preparation_time,delivery_time
0,1477147,337525,Hangawi,Korean,30.75,Weekend,Not given,25,20
1,1477685,358141,Blue Ribbon Sushi Izakaya,Japanese,12.08,Weekend,Not given,25,23
2,1477070,66393,Cafe Habana,Mexican,12.23,Weekday,5,23,28
3,1477334,106968,Blue Ribbon Fried Chicken,American,29.20,Weekend,3,25,15
4,1478249,76942,Dirty Bird to Go,American,11.59,Weekday,4,25,24

In [6]:
#CHECKING FOR THE SHAPE OF THE DATASET
df.shape

(1898, 9)

In [7]:
#CHECKIGNG FOR THE STATISTICAL SUMMERY OF THE DATASET
df.describe()

,order_id,customer_id,cost_of_the_order,food_preparation_time,delivery_time
count,1.898000e+03,1898.000000,1898.000000,1898.000000,1898.000000
mean,1.477496e+06,171168.478398,16.498851,27.371970,24.161749
std,5.480497e+02,113698.139743,7.483812,4.632481,4.972637
min,1.476547e+06,1311.000000,4.470000,20.000000,15.000000
25%,1.477021e+06,77787.750000,12.080000,23.000000,20.000000
50%,1.477496e+06,128600.000000,14.140000,27.000000,25.000000
75%,1.477970e+06,270525.000000,22.297500,31.000000,28.000000
max,1.478444e+06,405334.000000,35.410000,35.000000,33.000000

In [8]:
#CHECKING FOR DATA TYEPES OF THE DATA FRAME COLUMNS
df.dtypes

order_id                   int64
customer_id                int64
restaurant_name           object
cuisine_type              object
cost_of_the_order        float64
day_of_the_week           object
rating                    object
food_preparation_time      int64
delivery_time              int64
dtype: object

In [14]:
#CHECKING FOR THE INFORMATION ABOUT THE DATASET 
df.info;

In [11]:
df.describe(include = 'object')

       restaurant_name cuisine_type day_of_the_week     rating
count             1898         1898            1898       1898
unique             178           14               2          4
top        Shake Shack     American         Weekend  Not given
freq               219          584            1351        736

In [12]:
#CHECKING FOR WHETHER SOME OF THE COLUMNS IS HAVING A MISSING VALUES
df.isna().sum()

order_id                 0
customer_id              0
restaurant_name          0
cuisine_type             0
cost_of_the_order        0
day_of_the_week          0
rating                   0
food_preparation_time    0
delivery_time            0
dtype: int64

In [13]:
#CHECKING WHETHER A COLUMN IS HAVEING DUPLICATES
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1893    False
1894    False
1895    False
1896    False
1897    False
Length: 1898, dtype: bool